// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQ1LrXAy0UUf4_lDeXiUp0jHdXZDExY8',
    appId: '1:499960298571:web:6210dad91a4a958bbc21ce',
    messagingSenderId: '499960298571',
    projectId: 'pictionis-bee13',
    authDomain: 'pictionis-bee13.firebaseapp.com',
    storageBucket: 'pictionis-bee13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbV6soprHi_a6GrADfFRHePyVSqqJmIXI',
    appId: '1:499960298571:android:59591784c783882abc21ce',
    messagingSenderId: '499960298571',
    projectId: 'pictionis-bee13',
    storageBucket: 'pictionis-bee13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxsatve8gNje5tAu0ii0CtD6E-U--e2g',
    appId: '1:499960298571:ios:528ef69ad1d0c059bc21ce',
    messagingSenderId: '499960298571',
    projectId: 'pictionis-bee13',
    storageBucket: 'pictionis-bee13.appspot.com',
    iosClientId: '499960298571-2saqph0r4voohf0u7hhnpdj8db8e57nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictionis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxsatve8gNje5tAu0ii0CtD6E-U--e2g',
    appId: '1:499960298571:ios:528ef69ad1d0c059bc21ce',
    messagingSenderId: '499960298571',
    projectId: 'pictionis-bee13',
    storageBucket: 'pictionis-bee13.appspot.com',
    iosClientId: '499960298571-2saqph0r4voohf0u7hhnpdj8db8e57nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pictionis',
  );
}
